/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/crypto/market": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all cryptocurrency market data
         * @description Returns a list of all cryptocurrencies with their current market data including prices, changes, and chart data
         */
        get: operations["getCryptoMarket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crypto/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cryptocurrency by ID
         * @description Returns detailed information about a specific cryptocurrency
         */
        get: operations["getCryptoById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crypto/{id}/chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get chart data for cryptocurrency
         * @description Returns historical price chart data for a specific cryptocurrency
         */
        get: operations["getCryptoChart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CryptoData: {
            /**
             * @description Unique identifier for the cryptocurrency
             * @example bitcoin
             */
            id: string;
            /**
             * @description Full name of the cryptocurrency
             * @example Bitcoin
             */
            name: string;
            /**
             * @description Trading symbol
             * @example BTC
             */
            symbol: string;
            /**
             * @description Trading pair
             * @example BTC/JPY
             */
            pair: string;
            /**
             * @description Icon character or emoji
             * @example ₿
             */
            icon: string;
            /**
             * @description Hex color code for the icon background
             * @example #f7931a
             */
            iconColor: string;
            /**
             * Format: double
             * @description Current price in JPY
             * @example 9850000
             */
            currentPrice: number;
            /**
             * Format: double
             * @description Percentage change (positive or negative)
             * @example 5.2
             */
            changePercent: number;
            /** @description Array of chart data points */
            chartData: components["schemas"]["ChartDataPoint"][];
        };
        ChartDataPoint: {
            /**
             * @description Day label (Mon, Tue, Wed, etc.)
             * @example Mon
             */
            day: string;
            /**
             * Format: double
             * @description Price at this data point
             * @example 9350000
             */
            price: number;
        };
        MarketResponse: {
            /** @description Array of cryptocurrency market data */
            data: components["schemas"]["CryptoData"][];
            /**
             * Format: int64
             * @description Unix timestamp of the response
             * @example 1704067200
             */
            timestamp: number;
        };
        ChartResponse: {
            /** @description Array of chart data points */
            data: components["schemas"]["ChartDataPoint"][];
            /**
             * @description Time period of the chart data
             * @example 7d
             * @enum {string}
             */
            period: "24h" | "7d" | "30d" | "1y" | "all";
        };
        ErrorResponse: {
            /**
             * @description Error type
             * @example NOT_FOUND
             */
            error: string;
            /**
             * @description Human-readable error message
             * @example Cryptocurrency not found
             */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCryptoMarket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCryptoById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cryptocurrency ID (e.g., bitcoin, ethereum) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CryptoData"];
                };
            };
            /** @description Cryptocurrency not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCryptoChart: {
        parameters: {
            query?: {
                /** @description Time period for chart data */
                period?: "24h" | "7d" | "30d" | "1y" | "all";
            };
            header?: never;
            path: {
                /** @description Cryptocurrency ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartResponse"];
                };
            };
            /** @description Cryptocurrency not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
