/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/crypto/market": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all cryptocurrency market data
         * @description Returns a list of all cryptocurrencies with their current market data including prices, changes, and chart data
         */
        get: operations["getCryptoMarket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crypto/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cryptocurrency by ID
         * @description Returns detailed information about a specific cryptocurrency
         */
        get: operations["getCryptoById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crypto/{id}/chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get chart data for cryptocurrency
         * @description Returns historical price chart data for a specific cryptocurrency
         */
        get: operations["getCryptoChart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new order
         * @description Creates a new limit order for cryptocurrency trading
         */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user balance
         * @description Returns the current available balance for the authenticated user
         */
        get: operations["getBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trade-history/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get trade statistics
         * @description Returns aggregated trade statistics including total profit, execution count, and profit percentage
         */
        get: operations["getTradeStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trade-history/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get trade transaction log
         * @description Returns a paginated list of trade transactions with filtering options
         */
        get: operations["getTradeTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current unfilled orders
         * @description Returns current unfilled buy and sell orders from Bitflyer Lightning API, sorted by creation date (newest first) and limited to 10 orders per type
         */
        get: operations["getCurrentOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CryptoData: {
            /**
             * @description Unique identifier for the cryptocurrency
             * @example bitcoin
             */
            id: string;
            /**
             * @description Full name of the cryptocurrency
             * @example Bitcoin
             */
            name: string;
            /**
             * @description Trading symbol
             * @example BTC
             */
            symbol: string;
            /**
             * @description Trading pair
             * @example BTC/JPY
             */
            pair: string;
            /**
             * @description Icon character or emoji
             * @example ₿
             */
            icon: string;
            /**
             * @description Hex color code for the icon background
             * @example #f7931a
             */
            iconColor: string;
            /**
             * Format: double
             * @description Current price in JPY
             * @example 9850000
             */
            currentPrice: number;
            /**
             * Format: double
             * @description Percentage change (positive or negative)
             * @example 5.2
             */
            changePercent: number;
            /** @description Array of chart data points */
            chartData: components["schemas"]["ChartDataPoint"][];
        };
        ChartDataPoint: {
            /**
             * @description Day label (Mon, Tue, Wed, etc.)
             * @example Mon
             */
            day: string;
            /**
             * Format: double
             * @description Price at this data point
             * @example 9350000
             */
            price: number;
        };
        MarketResponse: {
            /** @description Array of cryptocurrency market data */
            data: components["schemas"]["CryptoData"][];
            /**
             * Format: int64
             * @description Unix timestamp of the response
             * @example 1704067200
             */
            timestamp: number;
        };
        ChartResponse: {
            /** @description Array of chart data points */
            data: components["schemas"]["ChartDataPoint"][];
            /**
             * @description Time period of the chart data
             * @example 7d
             * @enum {string}
             */
            period: "24h" | "7d" | "30d" | "1y" | "all";
        };
        CreateOrderRequest: {
            /**
             * @description Trading pair
             * @example BTC/JPY
             * @enum {string}
             */
            pair: "BTC/JPY" | "ETH/JPY";
            /**
             * @description Order type (currently only limit orders supported)
             * @example limit
             * @enum {string}
             */
            orderType: "limit";
            /**
             * Format: double
             * @description Limit price in JPY
             * @example 14000000
             */
            price: number;
            /**
             * Format: double
             * @description Amount of cryptocurrency to buy
             * @example 0.001
             */
            amount: number;
        };
        Order: {
            /**
             * Format: uuid
             * @description Unique order identifier
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            orderId: string;
            /**
             * @description Trading pair
             * @example BTC/JPY
             * @enum {string}
             */
            pair: "BTC/JPY" | "ETH/JPY";
            /**
             * @description Order type
             * @example limit
             * @enum {string}
             */
            orderType: "limit";
            /**
             * Format: double
             * @description Limit price in JPY
             * @example 14000000
             */
            price: number;
            /**
             * Format: double
             * @description Amount of cryptocurrency
             * @example 0.001
             */
            amount: number;
            /**
             * Format: double
             * @description Estimated total cost in JPY (price * amount)
             * @example 14000
             */
            estimatedTotal: number;
            /**
             * @description Order status
             * @example pending
             * @enum {string}
             */
            status: "pending" | "completed" | "cancelled" | "failed";
            /**
             * Format: date-time
             * @description Order creation timestamp
             * @example 2024-01-01T00:00:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Order last update timestamp
             * @example 2024-01-01T00:00:00Z
             */
            updatedAt?: string;
        };
        Balance: {
            /**
             * Format: double
             * @description Available balance in JPY
             * @example 1540200
             */
            availableBalance: number;
            /**
             * @description Currency code
             * @example JPY
             * @enum {string}
             */
            currency: "JPY";
            /**
             * Format: int64
             * @description Unix timestamp of the balance snapshot
             * @example 1704067200
             */
            timestamp: number;
        };
        TradeStatistics: {
            /**
             * Format: double
             * @description Total profit in JPY (rounded to 1 decimal place)
             * @example 115700
             */
            total_profit: number;
            /**
             * Format: double
             * @description Profit percentage (rounded to 1 decimal place)
             * @example 11.6
             */
            profit_percentage: number;
            /**
             * @description Total number of executed trades
             * @example 12
             */
            execution_count: number;
            /**
             * @description Time period for the statistics
             * @example all
             * @enum {string}
             */
            period: "all" | "7days";
        };
        Transaction: {
            /**
             * @description Unique transaction identifier
             * @example 1
             */
            id: string;
            /**
             * @description Cryptocurrency name
             * @example Bitcoin
             * @enum {string}
             */
            cryptocurrency: "Bitcoin" | "Ethereum";
            /**
             * Format: date-time
             * @description Transaction timestamp
             * @example 2024-12-10T14:30:00Z
             */
            timestamp: string;
            /**
             * Format: double
             * @description Profit amount in JPY (rounded to 1 decimal place)
             * @example 45000
             */
            profit: number;
            /**
             * @description Order type (always sell for completed trades)
             * @example sell
             * @enum {string}
             */
            order_type: "sell";
            /**
             * @description Sell order ID
             * @example #BF-88219
             */
            order_id: string;
            /**
             * Format: double
             * @description Buy price in JPY
             * @example 5800000
             */
            buy_price: number;
            /**
             * Format: double
             * @description Sell price in JPY
             * @example 6100000
             */
            sell_price: number;
            /**
             * Format: double
             * @description Amount of cryptocurrency traded
             * @example 0.15
             */
            amount: number;
            /**
             * @description Related buy order ID
             * @example #BF-88218
             */
            buy_order_id: string;
        };
        Pagination: {
            /**
             * @description Current page number
             * @example 1
             */
            current_page: number;
            /**
             * @description Total number of pages
             * @example 2
             */
            total_pages: number;
            /**
             * @description Total number of transactions
             * @example 12
             */
            total_count: number;
            /**
             * @description Whether there are more pages available
             * @example true
             */
            has_next: boolean;
        };
        TransactionLogResponse: {
            /** @description Array of trade transactions */
            transactions: components["schemas"]["Transaction"][];
            pagination: components["schemas"]["Pagination"];
        };
        CurrentOrder: {
            /**
             * @description Unique order identifier from Bitflyer
             * @example JRF20150707-050237-639234
             */
            id: string;
            /**
             * @description Order type
             * @example buy
             * @enum {string}
             */
            type: "buy" | "sell";
            /**
             * @description Trading pair
             * @example BTC/JPY
             * @enum {string}
             */
            pair: "BTC/JPY" | "ETH/JPY";
            /**
             * Format: double
             * @description Order price in JPY
             * @example 14000000
             */
            price: number;
            /**
             * Format: double
             * @description Order amount in cryptocurrency units
             * @example 0.001
             */
            amount: number;
            /**
             * Format: date-time
             * @description Order creation timestamp in ISO 8601 format
             * @example 2024-12-14T12:30:00Z
             */
            createdAt: string;
        };
        CurrentOrdersResponse: {
            /** @description List of current buy orders, sorted by creation date (newest first) */
            buyOrders: components["schemas"]["CurrentOrder"][];
            /** @description List of current sell orders, sorted by creation date (newest first) */
            sellOrders: components["schemas"]["CurrentOrder"][];
            /**
             * Format: int64
             * @description Unix timestamp when the data was retrieved
             * @example 1702555800
             */
            timestamp: number;
            /**
             * @description Trading pair filter that was applied (only present if pair parameter was specified)
             * @example BTC_JPY
             * @enum {string}
             */
            pair?: "BTC_JPY" | "ETH_JPY";
        };
        ErrorResponse: {
            /**
             * @description Error type
             * @example INSUFFICIENT_BALANCE
             * @enum {string}
             */
            error: "NOT_FOUND" | "BAD_REQUEST" | "INVALID_REQUEST" | "INVALID_AMOUNT" | "INVALID_PRICE" | "UNSUPPORTED_PAIR" | "INSUFFICIENT_BALANCE" | "UNAUTHORIZED" | "INTERNAL_ERROR" | "INTERNAL_SERVER_ERROR" | "INVALID_FILTER" | "INVALID_PAGINATION";
            /**
             * @description Human-readable error message
             * @example Available balance is insufficient for this order
             */
            message: string;
            /** @description Additional error details (optional) */
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCryptoMarket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCryptoById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cryptocurrency ID (e.g., bitcoin, ethereum) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CryptoData"];
                };
            };
            /** @description Cryptocurrency not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCryptoChart: {
        parameters: {
            query?: {
                /** @description Time period for chart data */
                period?: "24h" | "7d" | "30d" | "1y" | "all";
            };
            header?: never;
            path: {
                /** @description Cryptocurrency ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartResponse"];
                };
            };
            /** @description Cryptocurrency not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description Order created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Insufficient balance */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getBalance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Balance"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getTradeStatistics: {
        parameters: {
            query?: {
                /** @description Filter by cryptocurrency asset */
                asset_filter?: "all" | "BTC" | "ETH";
                /** @description Filter by time period */
                time_filter?: "all" | "7days";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeStatistics"];
                };
            };
            /** @description Invalid filter parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getTradeTransactions: {
        parameters: {
            query?: {
                /** @description Filter by cryptocurrency asset */
                asset_filter?: "all" | "BTC" | "ETH";
                /** @description Filter by time period */
                time_filter?: "all" | "7days";
                /** @description Page number for pagination */
                page?: number;
                /** @description Number of transactions per page */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionLogResponse"];
                };
            };
            /** @description Invalid filter or pagination parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCurrentOrders: {
        parameters: {
            query?: {
                /** @description Trading pair filter. If omitted, returns orders for both pairs */
                pair?: "BTC_JPY" | "ETH_JPY";
                /** @description Maximum number of orders per type (buy/sell) to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentOrdersResponse"];
                };
            };
            /** @description Invalid request parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized - invalid or missing authentication */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
