/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/crypto/market": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all cryptocurrency market data
         * @description Returns a list of all cryptocurrencies with their current market data including prices, changes, and chart data
         */
        get: operations["getCryptoMarket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crypto/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cryptocurrency by ID
         * @description Returns detailed information about a specific cryptocurrency
         */
        get: operations["getCryptoById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crypto/{id}/chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get chart data for cryptocurrency
         * @description Returns historical price chart data for a specific cryptocurrency
         */
        get: operations["getCryptoChart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new order
         * @description Creates a new limit order for cryptocurrency trading
         */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user balance
         * @description Returns the current available balance for the authenticated user
         */
        get: operations["getBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CryptoData: {
            /**
             * @description Unique identifier for the cryptocurrency
             * @example bitcoin
             */
            id: string;
            /**
             * @description Full name of the cryptocurrency
             * @example Bitcoin
             */
            name: string;
            /**
             * @description Trading symbol
             * @example BTC
             */
            symbol: string;
            /**
             * @description Trading pair
             * @example BTC/JPY
             */
            pair: string;
            /**
             * @description Icon character or emoji
             * @example ₿
             */
            icon: string;
            /**
             * @description Hex color code for the icon background
             * @example #f7931a
             */
            iconColor: string;
            /**
             * Format: double
             * @description Current price in JPY
             * @example 9850000
             */
            currentPrice: number;
            /**
             * Format: double
             * @description Percentage change (positive or negative)
             * @example 5.2
             */
            changePercent: number;
            /** @description Array of chart data points */
            chartData: components["schemas"]["ChartDataPoint"][];
        };
        ChartDataPoint: {
            /**
             * @description Day label (Mon, Tue, Wed, etc.)
             * @example Mon
             */
            day: string;
            /**
             * Format: double
             * @description Price at this data point
             * @example 9350000
             */
            price: number;
        };
        MarketResponse: {
            /** @description Array of cryptocurrency market data */
            data: components["schemas"]["CryptoData"][];
            /**
             * Format: int64
             * @description Unix timestamp of the response
             * @example 1704067200
             */
            timestamp: number;
        };
        ChartResponse: {
            /** @description Array of chart data points */
            data: components["schemas"]["ChartDataPoint"][];
            /**
             * @description Time period of the chart data
             * @example 7d
             * @enum {string}
             */
            period: "24h" | "7d" | "30d" | "1y" | "all";
        };
        CreateOrderRequest: {
            /**
             * @description Trading pair
             * @example BTC/JPY
             * @enum {string}
             */
            pair: "BTC/JPY" | "ETH/JPY";
            /**
             * @description Order type (currently only limit orders supported)
             * @example limit
             * @enum {string}
             */
            orderType: "limit";
            /**
             * Format: double
             * @description Limit price in JPY
             * @example 14000000
             */
            price: number;
            /**
             * Format: double
             * @description Amount of cryptocurrency to buy
             * @example 0.001
             */
            amount: number;
        };
        Order: {
            /**
             * Format: uuid
             * @description Unique order identifier
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            orderId: string;
            /**
             * @description Trading pair
             * @example BTC/JPY
             * @enum {string}
             */
            pair: "BTC/JPY" | "ETH/JPY";
            /**
             * @description Order type
             * @example limit
             * @enum {string}
             */
            orderType: "limit";
            /**
             * Format: double
             * @description Limit price in JPY
             * @example 14000000
             */
            price: number;
            /**
             * Format: double
             * @description Amount of cryptocurrency
             * @example 0.001
             */
            amount: number;
            /**
             * Format: double
             * @description Estimated total cost in JPY (price * amount)
             * @example 14000
             */
            estimatedTotal: number;
            /**
             * @description Order status
             * @example pending
             * @enum {string}
             */
            status: "pending" | "completed" | "cancelled" | "failed";
            /**
             * Format: date-time
             * @description Order creation timestamp
             * @example 2024-01-01T00:00:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Order last update timestamp
             * @example 2024-01-01T00:00:00Z
             */
            updatedAt?: string;
        };
        Balance: {
            /**
             * Format: double
             * @description Available balance in JPY
             * @example 1540200
             */
            availableBalance: number;
            /**
             * @description Currency code
             * @example JPY
             * @enum {string}
             */
            currency: "JPY";
            /**
             * Format: int64
             * @description Unix timestamp of the balance snapshot
             * @example 1704067200
             */
            timestamp: number;
        };
        ErrorResponse: {
            /**
             * @description Error type
             * @example INSUFFICIENT_BALANCE
             * @enum {string}
             */
            error: "NOT_FOUND" | "BAD_REQUEST" | "INVALID_REQUEST" | "INVALID_AMOUNT" | "INVALID_PRICE" | "UNSUPPORTED_PAIR" | "INSUFFICIENT_BALANCE" | "UNAUTHORIZED" | "INTERNAL_ERROR" | "INTERNAL_SERVER_ERROR";
            /**
             * @description Human-readable error message
             * @example Available balance is insufficient for this order
             */
            message: string;
            /** @description Additional error details (optional) */
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCryptoMarket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCryptoById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cryptocurrency ID (e.g., bitcoin, ethereum) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CryptoData"];
                };
            };
            /** @description Cryptocurrency not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCryptoChart: {
        parameters: {
            query?: {
                /** @description Time period for chart data */
                period?: "24h" | "7d" | "30d" | "1y" | "all";
            };
            header?: never;
            path: {
                /** @description Cryptocurrency ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartResponse"];
                };
            };
            /** @description Cryptocurrency not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description Order created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Insufficient balance */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getBalance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Balance"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
